// AUTO-GENERATED by generate_data.py — do not edit by hand.
// Re-run:  nix run nixpkgs#python3 -- generate_data.py

window.ELECTION_DATA = {
  "meta": {
    "constituency": "0000",
    "source": "kosningaprof.ruv.is",
    "generated": "2026-05-15T21:20:53.736073Z"
  },
  "parties": [
    {
      "name": "Flokkur fólksins",
      "nameEn": "People's Party",
      "abbr": "F",
      "color": "#EFBB4E",
      "slug": "reykjavik-flokkur-folksins"
    },
    {
      "name": "Framsóknarflokkur",
      "nameEn": "Progressive Party",
      "abbr": "B",
      "color": "#9CCE82",
      "slug": "reykjavik-framsoknarflokkur"
    },
    {
      "name": "Góðan daginn",
      "nameEn": "Good Morning",
      "abbr": "G",
      "color": "#B8D43D",
      "slug": "reykjavik-godan-daginn"
    },
    {
      "name": "Miðflokkur",
      "nameEn": "Centre Party",
      "abbr": "M",
      "color": "#45AE9F",
      "slug": "reykjavik-midflokkur"
    },
    {
      "name": "Okkar borg",
      "nameEn": "Our City",
      "abbr": "R",
      "color": "#85D4EC",
      "slug": "reykjavik-okkar-borg"
    },
    {
      "name": "Píratar",
      "nameEn": "Pirate Party",
      "abbr": "P",
      "color": "#6F4B95",
      "slug": "reykjavik-piratar"
    },
    {
      "name": "Samfylkingin - jafnaðarflokkur Íslands",
      "nameEn": "Social Democrats",
      "abbr": "S",
      "color": "#C11C2E",
      "slug": "reykjavik-samfylkingin-jafnadarflokkur-islands"
    },
    {
      "name": "Sjálfstæðisflokkur",
      "nameEn": "Independence Party",
      "abbr": "D",
      "color": "#41569D",
      "slug": "reykjavik-sjalfstaedisflokkur"
    },
    {
      "name": "Sósíalistaflokkur Íslands",
      "nameEn": "Socialist Party",
      "abbr": "J",
      "color": "#910F16",
      "slug": "reykjavik-sosialistaflokkur-islands"
    },
    {
      "name": "Vinstrið",
      "nameEn": "Left Movement",
      "abbr": "A",
      "color": "#183F38",
      "slug": "reykjavik-vinstrid"
    },
    {
      "name": "Viðreisn",
      "nameEn": "Reform Party",
      "abbr": "C",
      "color": "#EE8648",
      "slug": "reykjavik-vidreisn"
    }
  ],
  "questions": [
    {
      "id": "35",
      "is": "Það er gott að búa í mínu sveitarfélagi.",
      "en": "It is good to live in my municipality.",
      "type": "PROPOSITION",
      "cat": "general"
    },
    {
      "id": "38",
      "is": "Ég er ánægð/ur með þá þjónustu sem sveitarfélagið veitir mér.",
      "en": "I am satisfied with the services provided by the municipality.",
      "type": "PROPOSITION",
      "cat": "general"
    },
    {
      "id": "40",
      "is": "Hvernig ættu skattar og gjöld að vera í sveitarfélaginu miðað við stöðuna í dag?",
      "en": "How should taxes and fees be compared to the current situation? (Range: Much lower → Much higher)",
      "type": "RANGE",
      "cat": "general"
    },
    {
      "id": "42",
      "is": "Þegar skipulögð er byggð í sveitarfélaginu ætti frekar að leggja áherslu á ný hverfi en þéttingu byggðar.",
      "en": "When planning residential development, the emphasis should be on new neighbourhoods rather than densification.",
      "type": "PROPOSITION",
      "cat": "housing"
    },
    {
      "id": "43",
      "is": "Fjölga ætti íbúakosningum svo að almenningur geti tekið meiri þátt í ákvörðunum í sveitarfélaginu.",
      "en": "Citizen referendums should be more frequent so residents can participate in municipal decisions.",
      "type": "PROPOSITION",
      "cat": "general"
    },
    {
      "id": "45",
      "is": "Sveitarfélögum ætti að vera skylt að lögum að sjá börnum fyrir leikskólavist frá tólf mánaða aldri.",
      "en": "Municipalities should be legally required to provide nursery school places from 12 months of age.",
      "type": "PROPOSITION",
      "cat": "children"
    },
    {
      "id": "47",
      "is": "Sveitarfélagið mitt ætti að bjóða heimgreiðslur til foreldra til að auðvelda þeim að vera heima með börnum frá því að fæðingarorlofi lýkur og fram að leikskólavist.",
      "en": "The municipality should offer home-care payments so parents can stay home from end of parental leave until nursery school.",
      "type": "PROPOSITION",
      "cat": "children"
    },
    {
      "id": "49",
      "is": "Hvetja ætti foreldra til að stytta vistunartíma leikskólabarna gegn afslætti af gjöldum.",
      "en": "Parents should be encouraged to shorten nursery school hours in return for fee discounts.",
      "type": "PROPOSITION",
      "cat": "children"
    },
    {
      "id": "50",
      "is": "Sveitarfélagið ætti að beita sér fyrir frekari útvistun verkefna sinna við rekstur leik- og grunnskóla",
      "en": "The municipality should pursue further outsourcing of nursery and primary school operations.",
      "type": "PROPOSITION",
      "cat": "children"
    },
    {
      "id": "51",
      "is": "Sveitarfélagið ætti að niðurgreiða íþrótta- og tómstundaiðkun barna meira en nú er gert.",
      "en": "The municipality should subsidise children's sports and leisure activities more than it does now.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "52",
      "is": "Verja ætti meira fé til að styðja menningarlíf í sveitarfélaginu.",
      "en": "More money should be spent supporting cultural life in the municipality.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "53",
      "is": "Hælisleitendur á barnsaldri ættu að fá sömu þjónustu í sveitarfélaginu og aðrir íbúar.",
      "en": "Child asylum-seekers should receive the same municipal services as other residents.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "54",
      "is": "Snjómokstur og götusópun er fullnægjandi í mínu sveitarfélagi.",
      "en": "Snow clearance and street cleaning is adequate in my municipality.",
      "type": "PROPOSITION",
      "cat": "general"
    },
    {
      "id": "55",
      "is": "Sveitarfélagið ætti að greiða leið nýrra fyrirtækja sem vilja hefja starfsemi á svæðinu, með fjárhagslegum ívilnunum",
      "en": "The municipality should ease the way for new businesses with financial incentives.",
      "type": "PROPOSITION",
      "cat": "general"
    },
    {
      "id": "57",
      "is": "Sveitarfélagið þarf að auka fjárhagsaðstoð við þá íbúa sem lifa undir fátæktarmörkum.",
      "en": "The municipality needs to increase financial assistance to residents living below the poverty line.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "59",
      "is": "Lengja ætti opnunartíma sundlauga, þótt það kosti sveitarfélög fé.",
      "en": "Swimming pool opening hours should be extended, even if it costs the municipality money.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "60",
      "is": "Sveitarfélög hafa gengið of langt í að skikka íbúa til að flokka sorp.",
      "en": "Municipalities have gone too far in forcing residents to sort their waste.",
      "type": "PROPOSITION",
      "cat": "environment"
    },
    {
      "id": "64",
      "is": "Sveitarfélög ættu að verja meira fé í þjónustu við eldri borgara.",
      "en": "Municipalities should spend more on services for the elderly.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "239",
      "is": "Sveitarfélög ættu að greiða eldri borgurum frístundastyrk.",
      "en": "Municipalities should pay elderly citizens a leisure grant.",
      "type": "PROPOSITION",
      "cat": "welfare"
    },
    {
      "id": "69",
      "is": "Sveitarfélagið á að taka þátt í svokölluðum samgöngusáttmála höfuðborgarsvæðisins.",
      "en": "The municipality should participate in the Capital Area Transport Accord.",
      "type": "PROPOSITION",
      "cat": "transport"
    },
    {
      "id": "70",
      "is": "Ljúka á við Borgarlínu í þeirri mynd sem núverandi áform gera ráð fyrir.",
      "en": "The Borgarlína (Bus Rapid Transit) project should be completed as currently planned.",
      "type": "PROPOSITION",
      "cat": "transport"
    },
    {
      "id": "72",
      "is": "Fækka á akreinum fyrir almenna bílaumferð til að búa til pláss fyrir sérakreinar fyrir strætó.",
      "en": "Car lanes should be reduced to make room for dedicated bus lanes.",
      "type": "PROPOSITION",
      "cat": "transport"
    },
    {
      "id": "77",
      "is": "Að minnsta kosti eitt bílastæði á að fylgja hverri íbúð í sveitarfélaginu.",
      "en": "At least one parking space should accompany every dwelling in the municipality.",
      "type": "PROPOSITION",
      "cat": "transport"
    },
    {
      "id": "78",
      "is": "Það eru of margir einkabílar í umferðinni.",
      "en": "There are too many private cars in traffic.",
      "type": "PROPOSITION",
      "cat": "transport"
    },
    {
      "id": "79",
      "is": "Það er rétt að takmarka aðgengi almennings að útivistarsvæðinu í Heiðmörk í þágu vatnsverndar.",
      "en": "It is right to restrict public access to the Heiðmörk nature reserve for water-source protection.",
      "type": "PROPOSITION",
      "cat": "environment"
    },
    {
      "id": "28",
      "is": "Hverfi Reykjavíkur njóta jafnræðis þegar kemur að þjónustu sem sveitarfélagið veitir.",
      "en": "[RVK] Reykjavík's neighbourhoods enjoy equal treatment in municipal services.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "29",
      "is": "Festa á svokallaða Reykjavíkurleið í leikskólamálum í sessi til framtíðar.",
      "en": "[RVK] The so-called Reykjavík Model for nursery schools should be made permanent.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "30",
      "is": "Koma þarf í veg fyrir fyrirhugaðar breytingar á skipulagi Suðurlandsbrautar.",
      "en": "[RVK] Planned changes to the layout of Suðurlandsbraut road must be prevented.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "31",
      "is": "Hætta á við fyrirhuguð Miklubrautargöng.",
      "en": "[RVK] The planned Miklubraut tunnel should be cancelled.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "32",
      "is": "Einkavæða ætti Orkuveitu Reykjavíkur",
      "en": "[RVK] Orkuveita Reykjavíkur (city energy utility) should be privatised.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "33",
      "is": "Reykjavíkurflugvöllur á að vera í Vatnsmýri til frambúðar.",
      "en": "[RVK] Reykjavík Airport should remain at Vatnsmýri indefinitely.",
      "type": "PROPOSITION",
      "cat": "rvk"
    },
    {
      "id": "240",
      "is": "Hver eru mikilvægustu kosningamálin?",
      "en": "Top priority issues (choose up to 3)",
      "type": "PRIORITY",
      "cat": "general"
    }
  ],
  "answers": {
    "35": [
      "C!",
      "C",
      "D",
      "C",
      "B",
      "D",
      "D!",
      "C",
      "B",
      "C",
      "D!"
    ],
    "38": [
      "C",
      "B",
      "B",
      "B",
      "A",
      "C",
      "C",
      "B",
      "B!",
      "B",
      "A!"
    ],
    "40": [
      "Óbreytt",
      "Lægra",
      "Óbreytt",
      "Lægra!",
      "Lægra",
      "Lægra",
      "Óbreytt",
      "Lægra",
      "Óbreytt!",
      "Óbreytt",
      "Óbreytt!"
    ],
    "42": [
      "D!",
      "D",
      "D",
      "D!",
      "D",
      "B",
      "C",
      "C",
      "C",
      "B",
      "C"
    ],
    "43": [
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "C",
      "B",
      "D",
      "D",
      "B"
    ],
    "45": [
      "C",
      "C",
      "D",
      "B",
      "D",
      "D!",
      "D!",
      "_",
      "A!",
      "B",
      "B"
    ],
    "47": [
      "D",
      "C",
      "D",
      "D!",
      "A",
      "C",
      "A!",
      "D",
      "C",
      "B",
      "A!"
    ],
    "49": [
      "C",
      "C",
      "D",
      "D",
      "A",
      "C",
      "B",
      "B",
      "D!",
      "B",
      "C"
    ],
    "50": [
      "C",
      "C",
      "C",
      "C",
      "D",
      "B",
      "A",
      "D",
      "A!",
      "A",
      "D!"
    ],
    "51": [
      "C",
      "C",
      "D",
      "D",
      "B",
      "D",
      "D!",
      "C",
      "C!",
      "D",
      "D"
    ],
    "52": [
      "C",
      "C",
      "D",
      "C",
      "C",
      "D",
      "D!",
      "C",
      "C",
      "D",
      "B"
    ],
    "53": [
      "D",
      "C",
      "D",
      "B",
      "D",
      "D",
      "D!",
      "C",
      "D!",
      "D",
      "D"
    ],
    "54": [
      "B",
      "B",
      "B",
      "A!",
      "A",
      "B",
      "B",
      "A",
      "A!",
      "B",
      "A"
    ],
    "55": [
      "B",
      "C",
      "D",
      "D!",
      "B",
      "C",
      "C!",
      "D",
      "A",
      "_",
      "A"
    ],
    "57": [
      "D",
      "C",
      "D",
      "C",
      "C",
      "D",
      "C",
      "B",
      "D!",
      "D",
      "C"
    ],
    "59": [
      "D",
      "C",
      "D",
      "D",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D!"
    ],
    "60": [
      "C",
      "B",
      "A",
      "C",
      "C",
      "A",
      "A",
      "B",
      "A",
      "B",
      "A"
    ],
    "64": [
      "D",
      "D",
      "D",
      "D",
      "C",
      "D",
      "C",
      "D",
      "D!",
      "D",
      "D"
    ],
    "239": [
      "D",
      "D",
      "D",
      "D",
      "C",
      "D",
      "C",
      "D",
      "C",
      "A",
      "B"
    ],
    "69": [
      "C",
      "D",
      "D",
      "B",
      "A",
      "D!",
      "D!",
      "C",
      "C",
      "D",
      "D!"
    ],
    "70": [
      "B",
      "B",
      "A",
      "A!",
      "A",
      "D",
      "D!",
      "A",
      "C",
      "D",
      "C"
    ],
    "72": [
      "A",
      "A",
      "A",
      "A!",
      "A",
      "C",
      "C",
      "A",
      "C",
      "D",
      "C"
    ],
    "77": [
      "D",
      "D",
      "D",
      "D!",
      "D",
      "_",
      "B",
      "D",
      "D",
      "B",
      "C!"
    ],
    "78": [
      "B",
      "B",
      "A",
      "A",
      "A",
      "D",
      "D!",
      "B",
      "C",
      "C",
      "D"
    ],
    "79": [
      "A",
      "B",
      "A",
      "A",
      "B",
      "B",
      "B",
      "A",
      "B",
      "B",
      "B"
    ],
    "28": [
      "B",
      "B",
      "D",
      "B",
      "A",
      "B",
      "C",
      "A",
      "A!",
      "B",
      "B"
    ],
    "29": [
      "C",
      "_",
      "A",
      "B",
      "A",
      "_",
      "C",
      "A",
      "C",
      "_",
      "A!"
    ],
    "30": [
      "D",
      "D!",
      "D",
      "D!",
      "D",
      "A",
      "B",
      "D",
      "_",
      "A",
      "B"
    ],
    "31": [
      "A",
      "A",
      "A",
      "A",
      "A",
      "A",
      "A!",
      "A",
      "_",
      "B",
      "A"
    ],
    "32": [
      "A",
      "A",
      "A",
      "A",
      "A",
      "A",
      "A!",
      "A",
      "A!",
      "A",
      "A"
    ],
    "33": [
      "D",
      "C",
      "A",
      "D",
      "D",
      "A",
      "A!",
      "C",
      "_",
      "B",
      "B"
    ],
    "240": [
      [
        "6",
        "8",
        "12"
      ],
      [
        "6",
        "9",
        "12"
      ],
      [
        "4",
        "6",
        "12"
      ],
      [
        "1",
        "4",
        "9"
      ],
      [
        "1",
        "6",
        "12"
      ],
      [
        "1",
        "6",
        "9"
      ],
      [
        "6",
        "9",
        "12"
      ],
      [
        "4",
        "9",
        "12"
      ],
      [
        "4",
        "6",
        "9"
      ],
      [
        "6"
      ],
      [
        "6",
        "9",
        "12"
      ]
    ]
  },
  "reasonings": {
    "35": [
      "In general, Reykjavík is a beautiful, quiet and good city.",
      null,
      "Although there are a lot of things you can do better, living in Iceland is usually very good.",
      "Reykjavík is a good city, but we must strive to make it better.",
      "Reykjavík is poorly run and poorly maintained, with little attention paid to the general population but more attention to the private interest.",
      null,
      null,
      "Reykjavík is a wonderful city, but the services provided to residents need to be improved.",
      null,
      "Reykjavík has everything it takes to be a community for all of us, but things need to improve in several areas, including housing.",
      null
    ],
    "38": [
      "Agree somewhat, but the systems need to work together and grab people when they need it",
      null,
      "There's a lot wrong with the program. Tips aren't being taken care of, and construction isn't being done according to the residents' will.",
      null,
      "There are so many things that can be improved, so it's hard to agree with them.",
      null,
      null,
      null,
      null,
      "Much is done well, but public services need further improvement, particularly regarding housing, welfare services, and support for children, the elderly, and people with disabilities. I am not satisfied with the situation in which we as a municipality have long waiting lists for basic services that should be taken for granted.",
      "There is far too long a wait for essential services for children, and basic neighbourhood services are inadequate."
    ],
    "40": [
      "Unchanged, and no further increase in response is required to ensure funds are allocated to basic services for residents instead of body or pet projects",
      null,
      "Given the situation, it's not possible to reduce taxes and fees, but that should always be the goal.",
      null,
      "The business is out of control and deep. Stopping this mismanagement should create a way to reduce the burden on residents",
      "It is considered important to consider targeted incentives for small and socially important businesses and activities, such as neighborhood services, sharing economy services, cultural, innovation and coworking spaces. Such activities can strengthen local communities, diversify urban life, and create value that will not be judged by financial returns alone.",
      null,
      null,
      "Capital income should be subject to municipal tax on an equal basis with other income. The tax rate on those who already pay should not be raised. Property taxes need to be graduated to curb the trend of individuals becoming landlords. Property taxes should be lowered for those who own only their own home.",
      "The Left Movement wants a municipal tax on capital income — it is fair and obvious that the wealthiest, whose income comes mainly from capital, should contribute to the common pool equally with others. This requires a legislative change in parliament, but the Left Movement argues clearly for fair taxation. With a self-evident municipal tax on capital income, it would be possible to lower service fees for residents. This should really have been two separate questions: one about taxes and one about fees.",
      "Reform's dream would be to lower the burden on residents. Given the current financial situation, it is difficult to cut municipal income tax and other taxes on residents and businesses."
    ],
    "42": [
      "Strongly agree, we need to break ground and work through the housing crisis and build housing based on residents' needs",
      null,
      "Public health considerations support building further dispersed and with sufficient outdoor spaces.  In addition, there is considerable condensation in the green areas of the former settlement.",
      null,
      null,
      null,
      null,
      null,
      "Densification is clearly needed, but it must go hand in hand with adequate infrastructure capacity.",
      "Both are clearly needed. Use existing infrastructure where possible to build even stronger neighbourhoods for more people who need housing, but in a rapidly growing city new areas must also be developed.",
      "We consider that most densification zones are already in the planning pipeline or under construction — for example Ártúnshöfði, Keldnaland, and Hallar."
    ],
    "43": [
      "Yes, I support this and reinvigorate the Neighborhood Councils and give them more independence",
      null,
      "We want to vote for the Residents' Council in each school district.  The Aboriginal Council has a great deal of power over the use of school premises after school hours.  Let's use our shared properties as a community space for residents.",
      "Very important to listen to the locals and has not been done",
      null,
      "For example, I want to vote for residents on opening hours for swimming pools and Ylstrandar. Let a local lead the way!",
      "Good local consultation is very important.  The CoR has to make decisions based on the overall interest, and not all issues are relevant to a population vote.",
      null,
      null,
      null,
      "Citizen referendums are a decent way to resolve large, specific issues, but consultation with residents is a better way to reach consensus and outcomes."
    ],
    "45": [
      null,
      "If the goal is to delete waiting lists, the legalization of the preschool level is irrelevant because the problem is that there is a shortage of staff in the preschools. The state has not mentioned how it intends to address the shortage of teachers, but is responsible for the university level itself. But if the goal is for the state to contribute more to the cost of running a preschool, that's a positive thing. However, there is no provision for increased financial lending in the financial plan for the next 5 years, so these are empty statements.",
      "This is also related to the fact that municipalities do not receive any proportion of municipal income for operating this service. No one would think of sending a 6 year old home due to a driving crew in elementary school.",
      "I want to see a wide range of solutions, not just on behalf of the municipality, independent kindergartens, allowances and midwives",
      "Today, that requirement is not possible as the financial security of the current majority in special interests hinders it. It would take 2-3 years to get this started after restructuring and building new kindergartens.",
      null,
      null,
      "This question is flawed. Legislation does not solve the nursery school problem, which is primarily a staffing crisis — today 2,600 nursery school teachers are needed but only around 80 graduate each year. The Independence Party wants to offer more diverse solutions for families after parental leave, such as home daycare, workplace daycare, home-care payments, and well-resourced nursery schools.",
      "Parental leave needs to be extended — it is far better for children's development and wellbeing to spend the first 18 months with their parents. Separation anxiety peaks between 10–18 months, so being away from close caregivers for long periods places a heavy burden on the child's nervous system.",
      "The state needs to come in with support and funding. It is reasonable to formally define this as the first level of schooling, but not necessarily to tie it to 12 months of age, as the diverse circumstances and needs of families and children must be taken into account. Nursery school is for children and we need to design the system around them. Working conditions must also be made adequate.",
      "Legislating nursery school as a compulsory level does not solve the staffing crisis or the mould problem in many school buildings — that is where the city's focus should be. Reform supports diverse childcare solutions to address the situation, such as workplace nurseries. Reform supports extending parental leave and increasing the number of nursery school teachers to meet demand."
    ],
    "47": [
      null,
      "Payments at home should be conditioned on both parents splitting the payments to reduce the risk of only working mothers. Home payments should also be conditioned on waiving them if a child is allocated nursery space in his or her neighbourhood.",
      "Of course, people should be able to choose whether they want to stay home with their child or send them to kindergarten while school is not legally compulsory except from the age of 6.",
      null,
      "There is every chance that this could hamper the structure of the system, and also that those who would need the service would need the option to pay in kind.",
      "The main focus should be that the state long for the maternity leave and legalize the preschool level. But in order to temporarily bridge the current state of the waiting list for preschool places, I am open to exploring the implementation of a \"rights protected bridge payment\" to parents, guardians and grandparents of children The aim is for the payments to ensure, as permitted by law and contract, pension contributions, possible union/fund entitlements and transparent tax treatment, following the model of parental leave payments.",
      null,
      null,
      "This is not a long-term solution, but a start to bridge the gap until parental leave is extended.",
      "Municipalities have a strong responsibility toward families with children. I believe funding should be prioritised for building and maintaining good nursery schools so they exist in every neighbourhood. At the same time, it is understandable that families are under great pressure making ends meet, which is why the city must prioritise nursery school development and do what it can to make nursery schools an attractive working environment that families can rely on.",
      "Home-care payments are a plaster on the wrong wound. They discourage the city from solving the childcare problem. Parents — mostly mothers — stay out of the labour market longer and accumulate neither income nor other entitlements in the meantime. Research shows that parent-child bonding depends on quality time together, which more adults than just parents can create with a child, not merely on the number of hours. But parental leave needs to be extended."
    ],
    "49": [
      null,
      "Most parents don't take full advantage of their children's listed length of stay. It involves a lot of extra costs incurred by the municipality and increases the burden on preschool staff. However, it's important to create an incentive to list the right length of stay, without overcharging your parents.",
      "As it stands, this is a very sensible measure and can be seen in Kópavogur.",
      null,
      null,
      null,
      "Income earners, single parents, and parents who can't afford a 36-hour work week must be considered.  The Reykjavík Way does that to a certain extent.",
      null,
      "Those who are able should shorten their children's nursery school hours.",
      "The ultimate goal is for nursery school to be free. Ways to improve working conditions must be found, and the city has taken steps in that direction. Now the effects of changes must be monitored for both staff and families.",
      "This approach is an example of freedom of choice, one of Reform's core principles — that payment is made for services rendered and parents receive a discount in return for shortening the nursery hours."
    ],
    "50": [
      null,
      "Progress wants to start collaborating with workplaces, NGOs and institutions on workplace preschools and opening daycare resources for the youngest children. A clear requirement would be professional work, supervision and the requirement that the child be guaranteed continuous and uninterrupted schooling regardless of the parent's job. This can be implemented by always leaving children disconnected from the workplace in each kindergarten or daycare resource.",
      "We want to diversify and refer to successful examples from Isaacschool, Verslunarskóli and HR. It must be ensured that non-discrimination applies to the admission of children to all schools and that they are allowed to study there as well as the more affluent ones.",
      null,
      "It is natural to provide the parties competent for such operations with an opportunity.",
      "I support diversity in professional schooling and respect the right of parents to choose. However, it is not considered a priority to be contributing specifically to further private activities in preschools and primary schools.",
      "I support our excellent independent kindergartens, but I don't see any reason for the city to resort specifically to further outsourcing.",
      null,
      null,
      null,
      "The situation in the city's schools is unacceptable. To solve the problem everyone must pull together: the city, businesses, and pioneers in education."
    ],
    "51": [
      null,
      null,
      "Leisure is very important",
      null,
      "Not very responsible, considering the mismanagement of recent years",
      null,
      null,
      null,
      null,
      "Yes, but other approaches should be found beyond simply relying on the leisure grant — for example finding ways to make participation less expensive.",
      "We want to maintain the current leisure grant for everyone and increase it for those who need it most — that increase should be means-tested."
    ],
    "52": [
      "More cultural events could be brought to the city's suburbs",
      null,
      null,
      null,
      "The first few years would be financially difficult after years gone by, so such support would not be very likely in the first few years.",
      "Investing in culture is important, but it has been shown that every dollar invested in the creative industries can be returned many times over, not only in income and jobs, but also in quality of life, city appeal, tourism, and community involvement.",
      null,
      null,
      null,
      null,
      "The City of Reykjavík's contributions to cultural affairs are already above the national average."
    ],
    "53": [
      null,
      null,
      null,
      "Asylum applications should not be processed in a way that allows families to stay here for long periods of time during this process",
      "At the expense of the state where the border is open",
      null,
      null,
      "A somewhat unclear question, but of course we want all children who move to Iceland to live in good conditions. The state bears responsibility for the fact that services for child asylum-seekers are not adequate today.",
      null,
      null,
      null
    ],
    "55": [
      "Rather, licensing issues and complexity in the system should be simplified and facilitated.  This will require additional construction of commercial buildings in the city.",
      "Lower property fees",
      null,
      "The city needs to dramatically improve the interface with a company, reduce slots, and, for example, reduce property fees",
      "If this is done, it shall be in absolute exceptional cases and shall take into account the city's need for the business in question.",
      "It is considered important to consider targeted incentives for small and socially important businesses and activities, such as neighborhood services, sharing economy services, cultural, innovation and coworking spaces. Such activities can strengthen local communities, diversify urban life, and create value that will not be judged by financial returns alone.",
      "We'll be rolling out simplified regulations and licensing to businesses. We will be joined by those who want to start a business, and in some cases financial incentives may apply.",
      "We want to attract businesses to the city with more commercial land, lower property taxes, and lower fees. I support such general incentives.",
      null,
      "I am not fully clear on what this entails. In my view it depends on the size of the companies. It is reasonable to give greater support to smaller businesses.",
      "Reform wants to simplify the system and create a framework for businesses generally to grow and thrive on their own terms."
    ],
    "57": [
      null,
      null,
      null,
      null,
      "It needs to be distinguished between who is responsible, the state or the CoR.",
      null,
      null,
      "The City of Reykjavík already provides the highest level of financial assistance of any municipality in the country.",
      null,
      null,
      null
    ],
    "59": [
      null,
      null,
      null,
      "It doesn't cost a lot of money, considering the inconvenience of the shortened population. By reducing the number of paid parking spaces, the city has given up far more revenue than the savings from the shortening",
      "Unblocking special holidays should be much longer than today",
      "Want to cast a residents' vote on opening hours for swimming pools and Ylstrandir - allowing residents to dominate I have also led the work on a new pool tariff, which is now in place as we are focused on increasing the one-off fee to actual costs so that irregular guests and travelers pay a fair price for their visits to boost their income, while we have significantly reduced the annual rate for regular guests and are also offering a subscription to swim for $2,833 per month for the first time.",
      null,
      null,
      null,
      null,
      null
    ],
    "60": [
      null,
      null,
      null,
      "Continued garbage management has often failed to justify the required sorting",
      "Waste incineration is a natural development and should have been built long ago. In doing so, the classification would change considerably.",
      null,
      null,
      null,
      null,
      "Access for residents to sort their waste needs to be improved in many areas. Neighbourhood recycling stations are far away for those without a car, and it is not acceptable to take large volumes of sorted waste on the bus.",
      null
    ],
    "64": [
      null,
      "Invest in infrastructure for health promotion and older people's togetherness. Outdoor exercise equipment in green areas, better maintaining walking paths, and sponsoring sports clubs to run inexpensive classes for older people.",
      null,
      null,
      null,
      null,
      null,
      null,
      "In particular, expanding home-care services and building more nursing homes run by the city.",
      null,
      null
    ],
    "239": [
      null,
      "The petition wants to establish an income-based recreation grant for seniors. $60,000 per year.",
      null,
      null,
      "How this would be done and what would be the standard for such payments had to be carefully considered.",
      null,
      "However, it would be necessary to analyze whether such a grant should be linked to earnings.",
      null,
      null,
      "The focus should be on accessible leisure activities and finding ways to make them cheap or free in all neighbourhoods of the city, rather than spending funds on subsidising leisure activities.",
      "If it comes to it, leisure grants for the elderly should be means-tested."
    ],
    "69": [
      null,
      "It is essential that the municipalities in the metropolitan area have a common vision and work together to improve traffic flow, as this is one common road network.",
      null,
      "The Transport Treaty needs to be revised to reflect the interests of smokers",
      "Part of the transportation pact includes walking and biking paths, bridges and footbridges as normal et to continue but the City Line project ceased.",
      "The capital needs a strong and diverse transportation infrastructure to improve the flow of traffic around the city. It includes high-quality modern public transportation to accommodate the growing population and car numbers, which add up to dozens of cars each week in the city. I believe it is important to continue construction under the Transport Convention, focusing on transparency, good execution, and consultation with residents. The goal needs to be a transportation system that serves different people's needs and reduces delays for all modes.",
      null,
      "We do however want to review the Transport Accord from the ground up, get clarity on financing, and better prioritise Reykjavík's projects. We want a broad range of good transport options that do not crowd each other out.",
      null,
      "The City of Reykjavík is already a party to the Transport Accord. Personally I am opposed to road tolls that the state has discussed imposing.",
      "Reform finds it irresponsible to tear up from the roots an agreement that all municipalities in the capital area and the state have been working under for the past 7 years. We cannot afford further delays when it comes to investment in transport."
    ],
    "70": [
      "We want to use the revision clause of the Transport Accord and make changes at Suðurlandsbraut and Höfðabyggð.",
      "Criticism from residents, businesses and service providers must be taken into account — for example at Suðurlandsbraut. It is important to change that road layout.",
      null,
      "It is possible to achieve comparable results in improving  public transport far more economically",
      "Drop off all ideas for City Line, but change public transportation and free buses",
      "The capital needs a strong and diverse transportation infrastructure to improve the flow of traffic around the city. This includes the City Line to accommodate the growing population and car numbers, which add up to dozens of cars each week in the city. The goal needs to be a transportation system that serves different people's needs and reduces delays for all modes.",
      null,
      "We want to redesign the Borgarlína BRT from scratch and introduce a new rapid-bus system on dedicated lanes that does not constrict traffic the way the current Suðurlandsbraut layout envisages.",
      null,
      "No more delays — we need better public transport!",
      "Acceptable solutions must be found for individual construction projects, but the overall plans must press ahead. Do not tear up from the roots an agreement that all municipalities have approved."
    ],
    "72": [
      null,
      null,
      null,
      null,
      "It would be absolutely crazy to center the City Line, and it would be far cheaper to have free rides and reorganize public transportation.",
      "The capital needs a strong and diverse transportation infrastructure to improve the flow of traffic around the city. It includes, among other things, specialty lines of the City Line to meet the growing population and car numbers, adding to the dozens of cars each week in the city. The goal needs to be a transportation system that serves different people's needs and reduces delays for all modes.",
      "Better public transport ensures greater capacity of the road network for all modes of transport, and especially for the private car.",
      "We want to introduce a new rapid-bus system on dedicated lanes that does not constrict general traffic.",
      null,
      "Doing so increases the options available to all of us.",
      "Where circumstances leave no other option."
    ],
    "77": [
      null,
      null,
      null,
      null,
      "Two parking spaces should accompany each apartment in new buildings.",
      null,
      "Most apartments have and will have at least 1 parking space, depending on apartment size and location.",
      null,
      null,
      null,
      "Reform wants to resume residency surveys where residents are asked how they want to live. In high-rise developments there are no street-level spaces, so it is important to guarantee spaces there."
    ],
    "78": [
      null,
      "Automobiles increase in line with population growth and are a natural part of urban society. It's important to build public transportation to give more people a viable option. This can help prevent multiple cars from being in every home.",
      null,
      null,
      "Icelanders are a nation of cars, so it's normal to have 1-2 cars in every home.",
      "According to data from the Icelandic Transport Authority, 63+ cars are added each week in the capital area.",
      null,
      null,
      null,
      null,
      null
    ],
    "79": [
      null,
      "It is important to elaborate a solution to this dispute so that both interests are fully taken into account. Those who want to enjoy the outdoors while at the same time ensuring the future safety of the metropolitan area's water bodies.",
      null,
      "The Centre Party emphasises public access to outdoor recreation. Surface water should not be used as drinking water. The same city-owned company is seeking to pump industrial CO₂ into the ground in Ölfus, where there are enormous fresh-water springs — those two goals are in conflict.",
      null,
      null,
      "This needs to be looked at in context. We should seek ways to keep Heiðmörk's outdoor spaces open to the public without jeopardising water conservation.",
      null,
      "After a meeting with the Forestry Association it became clear to me that the planned measures are not actually in the interest of water protection. There is a better way to source water in Heiðmörk that does not require restricting public access to the outdoor recreation area.",
      "This is a complex and important issue that requires careful thought. The water must be protected, but the approach must be very well designed with public health considerations and public access to a popular outdoor recreation area in mind.",
      null
    ],
    "28": [
      null,
      null,
      null,
      "Gunn Services has been misrepresented and needs to be corrected",
      null,
      null,
      "Neighborhoods vary greatly, and services may vary based on the needs of the neighborhood.  But the goal is for every neighborhood to have the services they need.",
      null,
      null,
      null,
      "Key infrastructure must be in place in all neighbourhoods — that is not the situation today."
    ],
    "29": [
      "Projects that need to be constantly evolving and possibly as a choice",
      "Try this, but re-evaluate the results and their impact on school and on families. No system is perfect, and part of improving services is constantly looking at the system critically.",
      null,
      "The Centre Party supports equal treatment of kindergartens regardless of their form and ownership.",
      "The City of Reykjavík should review the operating models of the kindergartens rather than give up and discriminate against parents.",
      "It is important to evaluate the performance of the Reykjavík route when data is available and make an informed decision as a result.",
      "The Reykjavik Way, which began on 1 April, will be reviewed during the election period once experience has been gained in this ideology.  We're not stuck in one solution.",
      null,
      "Yes, an arrangement like the Reykjavík Model is needed, but its results must be measured and adjusted based on the outcomes.",
      "It is not possible to commit to making something permanent when there is not yet sufficient experience of it. The effects of the changes must be actively monitored through regular data collection — for example surveys — so that the results can be used for improvement.",
      "The Reykjavík Model creates no flexibility or freedom for working parents in childcare and nursery school matters, and adds further stress for parents in an endless puzzle. The model falls harder on mothers."
    ],
    "30": [
      null,
      null,
      null,
      "There is a total railway accident on the rise that must be stopped. The activities of companies with around 2,400 employees will have a very difficult time for at least 5 years and permanent changes will spoil the possibilities of employment and traffic flow",
      "No City Line.",
      "Plots and city land along Suðurlandsbraut 4–32 currently have about 1,600 parking spaces. After consultation with plot-holders, parking there will be reduced by approximately 10%. There is also the possibility of building multi-storey car parks behind Suðurlandsbraut in at least eight locations, so the total number of spaces may even increase in the near future — even as car trips along Suðurlandsbraut are expected to fall by 5,000–7,000 once the Borgarlína BRT begins carrying 20,000 passengers per day.",
      "Stakeholders along Suðurlandsbraut must be consulted when formulating the implementation plan. Access to businesses and their properties must not be cut off. The planning concept may change as part of that process.",
      null,
      null,
      null,
      "It is very important to find ways to accommodate the views of business operators during construction — for example by phasing works and not closing off traffic and parking prematurely or unnecessarily."
    ],
    "31": [
      null,
      null,
      null,
      null,
      "The transportation routes that speed up public transit through the city should normally be worked out.",
      null,
      null,
      null,
      null,
      null,
      "We have waited long enough. It is very important to maintain momentum in the projects under the Transport Accord."
    ],
    "32": [
      null,
      "It is normal to check the feasibility of selling at least a part of the Fibre Optic as it is in a competitive market. It is also important to spread the risk of OR by the innovative company Carbix by bringing in shareholders in that company, although intellectual property rights remain with OR.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "33": [
      null,
      "Reykjavik Airport is supposed to be in Vatnsmýrin, as it plays a very important role for ambulance flights and is the hub of domestic flights as well as a teaching airport. If the state wants to build another equally good or better airport that can fulfil the role of Reykjavik Airport in the same way, then the application is in favor of moving it. But not until that airport is operational.",
      null,
      null,
      null,
      null,
      null,
      "Reykjavík Airport should remain at Vatnsmýri until a better alternative is found. Hvassahraun is no longer on the table, so it is clear the airport will stay in its current location for the duration of the planning period.",
      null,
      "Unnecessary air traffic must stop immediately — such as private jets and sightseeing flights — and a new home must be found for pilot training. While a permanent location for the airport is being found, it is natural to ensure that air ambulance and essential flights continue to have proper conditions.",
      "The airport should move when a better alternative is found in cooperation with the state and in accordance with the Reykjavík Master Plan."
    ],
    "240": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "All of this is important and different groups in society must be well cared for, but housing is the foundation for everything else.",
      null
    ]
  },
  "priorityCategories": {
    "1": "Public Transport",
    "2": "Employment",
    "3": "Local Character",
    "4": "Municipal Finances",
    "5": "Roads & Snow",
    "6": "Housing",
    "7": "Sports & Leisure",
    "8": "Elderly Affairs",
    "9": "Schools",
    "10": "Disability Affairs",
    "11": "Culture",
    "12": "Transport",
    "13": "Taxes & Fees",
    "14": "Waste Management"
  },
  "rangeEn": {
    "Mun lægra": "Much lower",
    "Lægra": "Lower",
    "Óbreytt": "Unchanged",
    "Hærra": "Higher",
    "Mun hærra": "Much higher"
  }
};
